### PR TITLE
Small things

### PR DESCRIPTION
**Pull request by inorganik**
Hey Marcel, here are some changes, let me know if you are ok with them or if I should undo any of them.

- changed option `delay` to `lastDigitDelay` to make it more clear what the option does. I was worried it could be confused with countUp delay, which delays the entire animation
- Changed the import in the README to match how most people will use it, plus it shows the package name
- I added a document title on your demo
- Re-arranged dependencies: 
  - Parcel is a dev dependency, because it's used to serve the demo, not needed for the package itself
  - Removed the @types/countup.js dev dependency, because types ship with countUp.js
- package.json: changed main to point to the minified file, since the build does not generate a umd file
- package.json: changed "demo" script to start, since packages usually have a start script and you can easily run it with just `yarn start` or `npm start`

### CODE REVIEW

**Comment by msoler75** [comment]
all ok! merged

**Comment by inorganik** [comment]
Hey @msoler75 can you do a quick `npm publish` so the updated README is displayed on npmjs.com?

**Comment by inorganik** [comment]
and also so the other changes are released. Thanks!

**Comment by msoler75** [comment]
done!

**Pull request merged**
